theme: minima
title: "Federico Fiorani"
description: "A brief description about myself, coming soon."
author:
  name: "Federico Fiorani"
  email: "f.fiorani@outlook.com"
  url: "https://github.com/FedericoFiorani"

  header_pages:
  - about.md
  - projects.md
  - contact.md

  social_links:
  - name: GitHub
    url: "https://github.com/your-username"
  - name: LinkedIn
    url: "https://linkedin.com/in/your-username"
  - name: Twitter
    url: "https://twitter.com/your-username"
